name: Quality Check PR
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    branches:
    - main

concurrency:
  group: qc-app-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: pnpm

    - name: Install Dependencies
      run: pnpm install

    - name: Run Lint
      run: pnpm run lint

  types:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: pnpm

    - name: Install Dependencies
      run: pnpm install

    - name: Run Types
      run: pnpm run types
